#!/usr/bin/env python3
"""Generates src/jp_font.rs from the GNU Unifont hex fonts.

Sources (https://unifoundry.com/unifont/, GPLv2+ with font embedding
exception — the exception explicitly permits embedding the font in any
document or program):
  tools/unifont_jp.hex.gz  16x16 Japanese subset (JIS-oriented)
  tools/unifont.hex.gz     full BMP, provides the 8x16 ASCII glyphs

Input format ("hex" text format): "CP:HHHH...HH" lines.
  16x16 glyphs: 32 hex chars = 16 rows x 16 bits, MSB first.
   8x16 glyphs: 16 hex chars = 16 rows x 8 bits,  bit 7 leftmost.
Output: src/jp_font.rs — a sorted codepoint index + 32-byte glyphs for
the Japanese subset, plus a flat 8x16 ASCII table (U+0020..U+007E) so
the console can render halfwidth ASCII at the same 16px row height as
the kana/kanji (Japanese text lines then share one visual size).

The Japanese subset covers:
  U+3000..U+303F  Japanese punctuation / symbols
  U+3041..U+309F  hiragana
  U+30A1..U+30FF  katakana
  U+FF01..U+FF5E  fullwidth ASCII
  U+4E00..U+9FFF  CJK ideographs (JIS X 0208 kanji live here)
Run from the repo root:  python3 tools/gen_jp_font.py
"""

import gzip
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_JP = os.path.join(HERE, "unifont_jp.hex.gz")
SRC_ASCII = os.path.join(HERE, "unifont.hex.gz")
OUT = os.path.join(HERE, "..", "src", "jp_font.rs")

# (lo, hi) inclusive codepoint ranges to keep.
RANGES = [
    (0x3000, 0x303F),
    (0x3041, 0x309F),
    (0x30A1, 0x30FF),
    (0xFF01, 0xFF5E),
    (0x4E00, 0x9FFF),
]


def parse_hex(path: str) -> dict:
    glyphs = {}
    with gzip.open(path, "rt", encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_str, hexbytes = line.split(":", 1)
            cp = int(cp_str, 16)
            data = bytes.fromhex(hexbytes)
            # Only full 16x16 glyphs (32 bytes); skip narrow/combining.
            if len(data) != 32:
                continue
            glyphs[cp] = data
    return glyphs


def parse_ascii8x16(path: str) -> dict:
    """8x16 glyphs (16 bytes, one byte per row, bit 7 leftmost)."""
    glyphs = {}
    with gzip.open(path, "rt", encoding="ascii") as f:
        for line in f:
            line = line.strip()
            if not line or ":" not in line:
                continue
            cp_str, hexbytes = line.split(":", 1)
            cp = int(cp_str, 16)
            data = bytes.fromhex(hexbytes)
            if len(data) != 16:
                continue
            glyphs[cp] = data
    return glyphs


def main() -> int:
    if not os.path.exists(SRC_JP) or not os.path.exists(SRC_ASCII):
        print(f"error: {SRC_JP} / {SRC_ASCII} not found (download from "
              "https://unifoundry.com/unifont/ and gzip them)", file=sys.stderr)
        return 1

    all_glyphs = parse_hex(SRC_JP)
    selected = {}
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            if cp in all_glyphs:
                selected[cp] = all_glyphs[cp]

    ascii_glyphs = parse_ascii8x16(SRC_ASCII)
    ascii_sel = {}
    for cp in range(0x20, 0x7F):
        if cp in ascii_glyphs:
            ascii_sel[cp] = ascii_glyphs[cp]

    cps = sorted(selected)
    n = len(cps)
    content = render(cps, selected, n, ascii_sel)
    write_if_changed(OUT, content)

    print(f"wrote {OUT}: {n} JP glyphs ({n * 32 / 1024:.0f} KiB) + "
          f"{len(ascii_sel)} 8x16 ASCII glyphs")
    return 0


def render(cps, selected, n, ascii_sel) -> str:
    lines = []
    lines.append("//! Auto-generated by tools/gen_jp_font.py from GNU Unifont JP")
    lines.append("//! + GNU Unifont (unifont-17.0.05, GPLv2+ with font embedding")
    lines.append("//! exception). 16x16 glyphs are 2 bytes per row (bit 15 =")
    lines.append("//! leftmost pixel); 8x16 ASCII is 1 byte per row (bit 7 =")
    lines.append("//! leftmost). Do not edit by hand; regenerate with `make gen`.")
    lines.append("")
    lines.append("pub const CELL_W: u32 = 16;")
    lines.append("pub const CELL_H: u32 = 16;")
    lines.append(f"pub const COUNT: usize = {n};")
    lines.append("")

    lines.append("/// Sorted Unicode codepoints; binary-search this to find")
    lines.append("/// the glyph index into GLYPHS.")
    lines.append(f"pub static CODEPOINTS: [u32; {n}] = [")
    for i in range(0, n, 12):
        chunk = ", ".join(f"0x{c:04X}" for c in cps[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("];")
    lines.append("")

    lines.append(f"pub static GLYPHS: [[u8; 32]; {n}] = [")
    for cp in cps:
        data = selected[cp]
        rows = []
        for row in range(16):
            hi, lo = data[row * 2], data[row * 2 + 1]
            rows.append(f"0x{hi:02X}, 0x{lo:02X}")
        lines.append(f"    [ // U+{cp:04X}")
        for r in range(0, 16, 4):
            lines.append(f"        {', '.join(rows[r:r + 4])},")
        lines.append("    ],")
    lines.append("];")
    lines.append("")

    lines.append("/// Returns the 16x16 glyph for `cp`, or None if the")
    lines.append("/// codepoint is outside the embedded Japanese subset.")
    lines.append("pub fn glyph(cp: u32) -> Option<&'static [u8; 32]> {")
    lines.append("    let mut lo = 0usize;")
    lines.append("    let mut hi = CODEPOINTS.len();")
    lines.append("    while lo < hi {")
    lines.append("        let mid = (lo + hi) / 2;")
    lines.append("        match CODEPOINTS[mid].cmp(&cp) {")
    lines.append("            core::cmp::Ordering::Less => lo = mid + 1,")
    lines.append("            core::cmp::Ordering::Greater => hi = mid,")
    lines.append("            core::cmp::Ordering::Equal => return Some(&GLYPHS[mid]),")
    lines.append("        }")
    lines.append("    }")
    lines.append("    None")
    lines.append("}")
    lines.append("")

    # 8x16 ASCII table, indexed by (byte - 0x20).
    lines.append("/// 8x16 halfwidth ASCII glyphs (U+0020..U+007E), one byte")
    lines.append("/// per row, bit 7 leftmost. Same design as the 16x16")
    lines.append("/// Japanese glyphs, so mixed text shares one row height.")
    lines.append(f"pub static ASCII8X16: [[u8; 16]; {len(ascii_sel)}] = [")
    for cp in range(0x20, 0x7F):
        data = ascii_sel.get(cp, bytes(16))
        lines.append(f"    [ // U+{cp:04X} {chr(cp)!r}")
        for r in range(0, 16, 4):
            part = ", ".join(f"0x{b:02X}" for b in data[r:r + 4])
            lines.append(f"        {part},")
        lines.append("    ],")
    lines.append("];")
    lines.append("")
    lines.append("/// 8x16 glyph for an ASCII byte (0x20..0x7E).")
    lines.append("pub fn glyph8x16(byte: u8) -> Option<&'static [u8; 16]> {")
    lines.append("    if (0x20..=0x7E).contains(&byte) {")
    lines.append("        Some(&ASCII8X16[(byte - 0x20) as usize])")
    lines.append("    } else {")
    lines.append("        None")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_if_changed(path: str, content: str) -> None:
    """Idempotent write: keeps the file's mtime unchanged when the
    generated content is identical, so `make gen` doesn't force a kernel
    rebuild on every invocation."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return
    except FileNotFoundError:
        pass
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        os.unlink(tmp)
        raise


if __name__ == "__main__":
    sys.exit(main())
