#!/usr/bin/env python3
"""Generates src/isr_stubs.asm and src/isr_table.rs (x86_64 IDT stubs for all 256 vectors)."""

ERR_CODE_VECTORS = {8, 10, 11, 12, 13, 14, 17, 21, 29, 30}


def gen_stubs(path):
    lines = []
    lines.append("")
    lines.append(".section .text")
    lines.append(".code64")
    lines.append("")
    lines.append(".macro ISR_NOERR index")
    lines.append("    .globl isr\\index")
    lines.append("    .type isr\\index, @function")
    lines.append("isr\\index:")
    lines.append("    pushq $0")
    lines.append("    pushq $\\index")
    lines.append("    jmp isr_common")
    lines.append(".endm")
    lines.append("")
    lines.append(".macro ISR_ERR index")
    lines.append("    .globl isr\\index")
    lines.append("    .type isr\\index, @function")
    lines.append("isr\\index:")
    lines.append("    pushq $\\index")
    lines.append("    jmp isr_common")
    lines.append(".endm")
    lines.append("")
    for v in range(256):
        macro = "ISR_ERR" if v in ERR_CODE_VECTORS else "ISR_NOERR"
        lines.append(f"{macro} {v}")
    lines.append("")
    lines.append("isr_common:")
    lines.append("    pushq %rbx")
    lines.append("    pushq %rax")
    lines.append("    pushq %rcx")
    lines.append("    pushq %rdx")
    lines.append("    pushq %rsi")
    lines.append("    pushq %rdi")
    lines.append("    pushq %rbp")
    lines.append("    pushq %r8")
    lines.append("    pushq %r9")
    lines.append("    pushq %r10")
    lines.append("    pushq %r11")
    lines.append("    pushq %r12")
    lines.append("    pushq %r13")
    lines.append("    pushq %r14")
    lines.append("    pushq %r15")
    lines.append("    movq %rsp, %rdi")
    lines.append("    call isr_dispatch")
    lines.append("    popq %r15")
    lines.append("    popq %r14")
    lines.append("    popq %r13")
    lines.append("    popq %r12")
    lines.append("    popq %r11")
    lines.append("    popq %r10")
    lines.append("    popq %r9")
    lines.append("    popq %r8")
    lines.append("    popq %rbp")
    lines.append("    popq %rdi")
    lines.append("    popq %rsi")
    lines.append("    popq %rdx")
    lines.append("    popq %rcx")
    lines.append("    popq %rax")
    lines.append("    popq %rbx")
    lines.append("    addq $16, %rsp")
    lines.append("    iretq")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def gen_table(path):
    lines = []
    lines.append("// This file is generated by tools/gen_isr.py - do not edit by hand.")
    lines.append("")
    lines.append("unsafe extern \"C\" {")
    for v in range(256):
        lines.append(f"    fn isr{v}();")
    lines.append("}")
    lines.append("")
    lines.append("pub(crate) static ISR_ENTRIES: [unsafe extern \"C\" fn(); 256] = [")
    for i in range(0, 256, 16):
        row = ", ".join(f"isr{v}" for v in range(i, min(i + 16, 256)))
        lines.append(f"    {row},")
    lines.append("];")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    import os

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    gen_stubs(os.path.join(root, "src", "isr_stubs.asm"))
    gen_table(os.path.join(root, "src", "isr_table.rs"))
    print("generated src/isr_stubs.asm and src/isr_table.rs")
